#!/bin/bash

# 前景色（普通）
red='\033[1;31m'
magenta='\033[0;1;35;95m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'

# 前景色（更亮/加粗）
red_fg_strong='\033[1;91m'
green_fg_strong='\033[1;92m'
yellow_fg_strong='\033[1;93m'
blue_fg_strong='\033[1;94m'

# 背景色
red_bg='\033[41m'
green_bg='\033[42m'
yellow_bg='\033[43m'
blue_bg='\033[44m'
light_cyan_bg='\033[106m'

# 复位
reset='\033[0m'


log() {
    current_time=$(date +'%H:%M:%S')
    case "$1" in
        "INFO")
            echo -e "${blue_bg}[$current_time]${reset} ${blue_fg_strong}[信息]${reset} $2"
            ;;
        "WARN")
            echo -e "${yellow_bg}[$current_time]${reset} ${yellow_fg_strong}[警告]${reset} $2"
            ;;
        "ERROR")
            echo -e "${red_bg}[$current_time]${reset} ${red_fg_strong}[错误]${reset} $2"
            ;;
        *)
            echo -e "${blue_bg}[$current_time]${reset} ${blue_fg_strong}[调试]${reset} $2"
            ;;
    esac
}

# 检查命令是否存在
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

for cmd in proot-distro; do
    command_exists "$cmd" || pkg install -y "$cmd"
done
log "INFO" "安装debian容器..."
if [ ! -d "$PREFIX/var/lib/proot-distro/installed-rootfs/debian/" ]; then
    pd i debian
    log "INFO" "安装完成!"
    else
    log "INFO" "发现现有debian容器,跳过安装"
fi

echo "pd login debian" >>"${PREFIX}/etc/termux-login.sh"
init_cmd="bash <(curl -sSL https://linuxmirrors.cn/main.sh) --pure-mode --protocol https --use-intranet-source true --backup false --upgrade-software true --clean-cache true && \
apt install -y sudo curl libgcrypt20 && \
curl -O https://raw.githubusercontent.com/NapNeko/NapCat-Installer/refs/heads/main/script/install.sh && \
echo \"alias NC='xvfb-run -a /root/Napcat/opt/QQ/qq --no-sandbox'\" >> ~/.bashrc && \
sudo bash install.sh --docker n --cli n --proxy 0"
pd sh debian -- bash -c "$init_cmd"
pd login debian