#!/data/data/com.termux/files/usr/bin/bash -e

echo -e "\033]0;MaiBot半自动安装\007"

# 前景色（普通）
red='\033[1;31m'
magenta='\033[0;1;35;95m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'

# 前景色（更亮/加粗）
red_fg_strong='\033[1;91m'
green_fg_strong='\033[1;92m'
yellow_fg_strong='\033[1;93m'
blue_fg_strong='\033[1;94m'

# 背景色
red_bg='\033[41m'
green_bg='\033[42m'
yellow_bg='\033[43m'
blue_bg='\033[44m'
light_cyan_bg='\033[106m'

# 复位
reset='\033[0m'


log() {
    current_time=$(date +'%H:%M:%S')
    case "$1" in
        "INFO")
            echo -e "${blue_bg}[$current_time]${reset} ${blue_fg_strong}[信息]${reset} $2"
            ;;
        "WARN")
            echo -e "${yellow_bg}[$current_time]${reset} ${yellow_fg_strong}[警告]${reset} $2"
            ;;
        "ERROR")
            echo -e "${red_bg}[$current_time]${reset} ${red_fg_strong}[错误]${reset} $2"
            ;;
        *)
            echo -e "${blue_bg}[$current_time]${reset} ${blue_fg_strong}[调试]${reset} $2"
            ;;
    esac
}

# 检查命令是否存在
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# 更新源到清华镜像
if ! grep -q "mirrors.tuna.tsinghua.edu.cn" "$PREFIX/etc/apt/sources.list"; then
    log "INFO" "更新软件源到清华镜像..."
    cp "$PREFIX/etc/apt/sources.list" "$PREFIX/etc/apt/sources.list.bak"
    sed -i 's@^\(deb.*stable main\)$@#\1\ndeb https://mirrors.tuna.tsinghua.edu.cn/termux/termux-packages-24 stable main@' "$PREFIX/etc/apt/sources.list"
fi

for cmd in proot-distro; do
    command_exists "$cmd" || pkg install -y "$cmd"
done

if [ -f "$PREFIX/etc/apt/sources.list.bak" ]; then
    mv "$PREFIX/etc/apt/sources.list.bak" "$PREFIX/etc/apt/sources.list"
fi

if [ ! -d "$PREFIX/var/lib/proot-distro/installed-rootfs/maibot/" ]; then
    log "INFO" "安装ubuntu容器..."
    export PD_OVERRIDE_TARBALL_URL="https://gh-proxy.com/https://raw.githubusercontent.com/Dong-Jing-Yu/Dong-Jing-Yu.github.io/refs/heads/main/Termux/proot-distro/ubuntu-noble-aarch64-pd-v4.18.0.tar.xz"
    proot-distro install ubuntu --override-alias maibot
    log "INFO" "安装完成!"
fi



init_cmd="cd ~ && \
apt update -y && \
apt install -y sudo vim git python3-dev python3.12-venv build-essential screen curl python3-pip && \
mkdir maimai && \
cd maimai && \
git clone https://gh-proxy.com/https://github.com/MaiM-with-u/MaiBot.git.git \
git clone https://gh-proxy.com/https://github.com/MaiM-with-u/MaiBot-Napcat-Adapter.git.git \
apt autoremove -y && \
apt clean && \
rm -rf /tmp/* /var/lib/apt/lists && \
pip3 install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple uv
"
proot-distro sh maibot -- bash -c "$init_cmd"

echo -e "${red}https://docs.mai-mai.org/manual/deployment/mmc_deploy_android.html#传统方式环境配置${reset}\n"
echo -e "脚本已执行到 ${green}安装 uv (推荐)${reset}\n"
echo -e "进入容器: ${green}proot-distro login nc${reset}\n"