#!/data/data/com.termux/files/usr/bin/bash -e

# 前景色（普通）
red='\033[1;31m'
magenta='\033[0;1;35;95m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'

# 前景色（更亮/加粗）
red_fg_strong='\033[1;91m'
green_fg_strong='\033[1;92m'
yellow_fg_strong='\033[1;93m'
blue_fg_strong='\033[1;94m'

# 背景色
red_bg='\033[41m'
green_bg='\033[42m'
yellow_bg='\033[43m'
blue_bg='\033[44m'
light_cyan_bg='\033[106m'

# 复位
reset='\033[0m'


log() {
    current_time=$(date +'%H:%M:%S')
    case "$1" in
        "INFO")
            echo -e "${blue_bg}[$current_time]${reset} ${blue_fg_strong}[信息]${reset} $2"
            ;;
        "WARN")
            echo -e "${yellow_bg}[$current_time]${reset} ${yellow_fg_strong}[警告]${reset} $2"
            ;;
        "ERROR")
            echo -e "${red_bg}[$current_time]${reset} ${red_fg_strong}[错误]${reset} $2"
            ;;
        *)
            echo -e "${blue_bg}[$current_time]${reset} ${blue_fg_strong}[调试]${reset} $2"
            ;;
    esac
}
    
# 更新源到清华镜像
if ! grep -q "mirrors.tuna.tsinghua.edu.cn" "$PREFIX/etc/apt/sources.list"; then
    log "INFO" "更新软件源到清华镜像..."
    cp "$PREFIX/etc/apt/sources.list" "$PREFIX/etc/apt/sources.list.bak"
    sed -i 's@^\(deb.*stable main\)$@#\1\ndeb https://mirrors.tuna.tsinghua.edu.cn/termux/termux-packages-24 stable main@' "$PREFIX/etc/apt/sources.list"

fi

for cmd in screen proot-distro; do
    command -v "$cmd" >/dev/null 2>&1 || pkg install -y "$cmd"
done
log "INFO" "安装debian容器..."
export PD_OVERRIDE_TARBALL_URL="https://gitee.com/Dong-Jing-Yu/Dong-Jing-Yu.github.io/raw/main/Termux/proot-distro/debian-bookworm-aarch64-pd-v4.17.3.tar.xz"
proot-distro install debian --override-alias nc
log "INFO" "安装完成!"
mv "$PREFIX/etc/apt/sources.list.bak" "$PREFIX/etc/apt/sources.list"


init_cmd="apt update -y && apt upgrade -y && \
apt install -y sudo curl && \
curl -O https://gitee.com/Dong-Jing-Yu/Dong-Jing-Yu.github.io/raw/main/Termux/napcat.sh && \
sudo bash napcat.sh --docker n --cli n && \
apt autoremove -y && \
apt clean && \
rm -rf /tmp/* /var/lib/apt/lists"
proot-distro sh napcat -- bash -c "$init_cmd"

echo -e "${red}napcat容器安装成功, 上方无效信息无需关注, 请参考下方说明⬇${reset}"

echo -e "\n安装完成, 请输入${green} proot-distro sh napcat -- bash -c \"xvfb-run -a qq --no-sandbox\" ${reset}命令启动。"
echo -e "保持后台运行 请输入${green} screen -dmS napcat bash -c 'proot-distro sh napcat -- bash -c \"xvfb-run -a qq --no-sandbox\"'${reset}"
echo -e "后台快速登录 请输入${green} screen -dmS napcat bash -c 'proot-distro sh napcat -- bash -c \"xvfb-run -a qq --no-sandbox -q QQ号码\"'${reset}"
echo -e "进入容器内部 请输入${green} proot-distro login napcat ${reset}"
echo -e "容器数据位置${magenta} /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/napcat${reset}"
echo -e "Napcat安装位置(容器外真实路径)${magenta} /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/napcat/opt/QQ/resources/app/app_launcher/napcat${reset}"
echo -e "注意, 您可以随时使用${green}screen -r napcat${reset}来进入后台进程并使用${green}ctrl + a + d${reset}离开(离开不会关闭后台进程)。"
echo -e "${green}WEB_UI访问密钥在上方信息中${reset}"